APP_NAME="Simantri PLUS"
APP_ENV=production
APP_KEY=base64:HNU+Nb2vC44ablVRvqG6bls7tdpBmPYSOJLU+4rR4sE=
APP_DEBUG=false
APP_URL=http://localhost
# APP_URL=https://kerjo.faskesku.com
URL_RADIOLOGI=http://172.16.10.10/webapps/radiologi/
LOGO_INSTANSI=img/logo/logo.png

LOG_CHANNEL=daily
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

# BPJS Configuration
# Format untuk kompatibilitas dengan trustmark BPJS
BPJS_PCARE_BASE_URL=https://apijkn.bpjs-kesehatan.go.id/pcare-rest
BPJS_PCARE_CONS_ID=7925
BPJS_PCARE_CONS_PWD=2eF2C8E837
BPJS_PCARE_USER_KEY=403bf17ddf158790afcfe1e8dd682a67
BPJS_PCARE_USER=11251616
BPJS_PCARE_PASS=Pcare152#
BPJS_PCARE_KODE_PPK=11251616
BPJS_PCARE_APP_CODE=095

BPJS_ICARE_BASE_URL=https://apijkn.bpjs-kesehatan.go.id/wsihs/api/pcare
BPJS_ICARE_CONS_ID=7925
BPJS_ICARE_CONS_PWD=2eF2C8E837
BPJS_ICARE_USER=siswo-11251616
BPJS_ICARE_PASS=Siswo102#
BPJS_ICARE_USER_KEY=403bf17ddf158790afcfe1e8dd682a67
BPJS_ICARE_APP_CODE=095

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=kerjo
DB_USERNAME=root
DB_PASSWORD=
DB_SOCKET=

BROADCAST_DRIVER=pusher
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=480
SESSION_DOMAIN=null
SESSION_SECURE_COOKIE=false

# Meningkatkan timeout
DB_TIMEOUT=60
SCRIPT_TIMEOUT=300
MAX_EXECUTION_TIME=300

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=1969029
PUSHER_APP_KEY=f88f81949e37f325e996
PUSHER_APP_SECRET=6930c49c64402e3a5652
PUSHER_APP_CLUSTER=ap1
PUSHER_SCHEME=https
PUSHER_APP_HOST=
PUSHER_APP_PORT=443

VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="${PUSHER_HOST}"
VITE_PUSHER_PORT="${PUSHER_PORT}"
VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

# SATUSEHAT Configuration
SATUSEHAT_API_URL=https://api-satusehat-stg.dto.kemkes.go.id
SATUSEHAT_AUTH_URL=https://api-satusehat-stg.dto.kemkes.go.id/oauth2/v1
SATUSEHAT_CLIENT_ID=CXVczABvJTnNGGfUiAXWOAQ2BANcCXZwvVBwi1XtIp8dJTAy
SATUSEHAT_CLIENT_SECRET=UnPTARJ4n2siglWxJ3y3HtlTM215cAagKF7ecf0jkOxl8Ty3AuxhFJdOYdZpKstZ
SATUSEHAT_ORGANIZATION_ID=100006530
SATUSEHAT_TOKEN=
SATUSEHAT_TOKEN_EXPIRY=3600

# # JKN Mobile API Configuration
# MOBILEJKN_API_URL=https://kerjo.simkeskhanza.com/MjknKhanza/antrean
# MOBILEJKN_AUTH_URL=https://kerjo.simkeskhanza.com/api-bpjsfktp/auth
# MOBILEJKN_API_USERNAME=password_asuransi.usere
# MOBILEJKN_API_PASSWORD=password_asuransi.passworde
# MOBILEJKN_API_TOKEN=

# # BPJS Antrol API Configuration
# BPJS_ANTROL_API_URL=https://kerjo.simkeskhanza.com/api-bpjsfktp
# BPJS_ANTROL_API_USERNAME=password_asuransi.usere
# BPJS_ANTROL_API_PASSWORD=password_asuransi.passworde
# BPJS_ANTROL_API_TOKEN=

# Mode Simulasi PCARE (untuk testing)
PCARE_SIMULATION_MODE=true

# BPJS Antrean V2 API Configuration
BPJS_ANTREAN_BASE_URL_V1=https://kerjo.simkeskhanza.com/api-bpjsfktp/
BPJS_ANTREAN_BASE_URL=https://kerjo.simkeskhanza.com/MjknKhanza/
BPJS_ANTREAN_AUTH_URL=https://kerjo.simkeskhanza.com/api-bpjsfktp/auth
BPJS_ANTREAN_USERNAME=kerjo
BPJS_ANTREAN_PASSWORD=empukjeruu
BPJS_ANTREAN_CONS_ID=7925
BPJS_ANTREAN_CONS_PWD=2eF2C8E837
BPJS_ANTREAN_USER_KEY=e0fc15a6c8f737a8c46d9072e63b6102
BPJS_ANTREAN_USER=siswo-11251616
BPJS_ANTREAN_PASS=Siswo102#

BPJS_ANTREAN_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJLaGFuemEgUkVTVCBBUEkiLCJhdWQiOiJDbGllbnQgS2hhbnphIFJFU1QgQVBJIiwiaWF0IjoxNzQyNzg2OTE3LCJleHAiOjM2NjAsImRhdGEiOnsidXNlcm5hbWUiOiJrZXJqbyJ9fQ.CqSOwMvjD6tGwztM22wnskiCbNpSSJBELQlfQq2C+9w
USE_MJKNKHANZA_WEBSERVICE=false

# BPJS Antrean MobileJKN Config
MOBILEJKN_API_URL=https://apijkn.bpjs-kesehatan.go.id/antreanfktp
MOBILEJKN_SECRET_KEY=2eF2C8E837
MOBILEJKN_CONS_ID=7925
MOBILEJKN_USER_KEY=e0fc15a6c8f737a8c46d9072e63b6102
MOBILEJKN_PASS=Siswo102#
MOBILEJKN_USER=siswo-11251616
MOBILEJKN_ADD_ANTRIAN=yes

# BPJS MobileJKN Config untuk WsBPJSController
BPJS_MOBILEJKN_BASE_URL=https://apijkn.bpjs-kesehatan.go.id/antreanfktp
BPJS_MOBILEJKN_CONS_ID=7925
BPJS_MOBILEJKN_CONS_PWD=2eF2C8E837
BPJS_MOBILEJKN_USER_KEY=e0fc15a6c8f737a8c46d9072e63b6102
BPJS_MOBILEJKN_USER=siswo-11251616
BPJS_MOBILEJKN_PASS=Siswo102#

# BPJS API Token dan Username untuk digunakan di Mobile JKN
BPJS_API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJLaGFuemEgUkVTVCBBUEkiLCJhdWQiOiJDbGllbnQgS2hhbnphIFJFU1QgQVBJIiwiaWF0IjoxNzQyNzg2OTE3LCJleHAiOjM2NjAsImRhdGEiOnsidXNlcm5hbWUiOiJrZXJq
BPJS_API_USERNAME=siswo-11251616

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
MOBILEJKN_API_URL=https://apijkn.bpjs-kesehatan.go.id/antreanfktp
BPJS_MOBILEJKN_BASE_URL=https://apijkn.bpjs-kesehatan.go.id/antreanfktp

# Flag untuk mengaktifkan/menonaktifkan debug logging terperinci
# Atur ke true untuk mengaktifkan, false untuk menonaktifkan
DEBUG_PATIENT_CONTROLLER=false
DEBUG_LOGIN_AUTH=false
